Safe v5 update
SAFE-Stack/SAFE-BookStore pull request #432
Opened 2024-01-19 14:27 UTC by martinbryant

2024-01-22 10:35 UTC, martinbryant commented
### Base page

- [ ] Navigation
- [ ] Logout

### Home page

- [ ] View
- [ ] Initial data

### Login page

- [ ] View
- [ ] Login

### Wishlist Page

- [ ] View
- [ ] Initial data
- [ ] Remove book
- [ ] New book

2024-01-26 17:38 UTC, martinbryant commented
### Tests

- [ ] Client
- [ ] Shared
- [ ] Server

### Other

- [ ] Auth on wishlist endpoint
- [ ] Function app working
- [ ] Hook up blob storage/test refactor

2024-02-23 13:52 UTC, isaacabraham approved these changes

2024-02-23 14:02 UTC, isaacabraham requested changes
* Docker container needs to be renamed.
* "Update" folder needs to be deleted.
* Cleanup of storage account fails every time
* Default title of web app

2024-02-23 16:05 UTC, isaacabraham approved these changes

2024-02-23 16:09 UTC, merged